title:             "Cornel's PlayGround"
email:             "onelife0985@gmail.com"
description:       "Sort of Scientific things"
author:            "Cornelii.G.Son"
baseurl:           "/"
url:               "http://cornelii.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
#markdown:          kramdown
markdown: redcarpet
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data", "fenced_code_blocks"]


# collections
collections_dir: mycollections
collections:
  EngMath:
    output: true
    permalink: /:name
  Control:
    output: true
    permalink: /:name
  RL:
    output: true
    permalink: /:name
  MoM:
    output: true
    permalink: /:name

  Django:
    output: true
    permalink: /:name
  
    